version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-poc
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
